version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service_db
      MYSQL_USER: garv
      MYSQL_PASSWORD: 420
    ports:
      - "5050:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
